# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-06 17:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='created_by',
            field=models.CharField(default=datetime.datetime(2019, 11, 6, 17, 41, 1, 20000, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
