# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-06 22:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_remove_receipe_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='user',
            field=models.CharField(default=datetime.datetime(2019, 11, 6, 22, 31, 35, 839000, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
